import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Col, Container, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import { BsSearch } from "react-icons/bs";
import { MdSend } from "react-icons/md";

export default function Home({
  userData,
  activeuserDataUser,
  chatactiveuserData,
}) {
  const router = useRouter();

  const [userList, setUser] = useState("");
  const [search, setSearch] = useState("")

  console.log(search)
  useEffect(() => {
    setUser(userData);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="bg-secondary"
        style={{ height: "100vh", color: "#838383" }}
      >
        <div className="pt-5">
          <Container>
            <Row>
              <Col
                md={4}
                className=" p-0 position-relative"
                style={{
                  maxHeight: "80vh",
                  background: "#f0f2f5",
                  borderRight: "1px solid #ddd",
                }}
              >
                <div className="d-flex align-items-center mx-2 my-3 px-3 px-2">
                  <div className="flex-shrink-0">
                    <img
                      src="https://dummyimage.com/50x50/000/fff"
                      alt="Profile"
                      className="rounded-circle"
                    />
                  </div>
                  <div className="flex-grow-1 ms-3">
                    {activeuserDataUser.name}
                  </div>
                </div>
                <form
                  className="d-flex border-bottom"
                  style={{ background: "#fff", padding: "10px" }}
                >
                  <div className="input-group">
                    <span className="input-group-text" id="basic-addon1">
                      <BsSearch />
                    </span>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="search"
                      aria-label="search"
                      aria-describedby="basic-addon1"
                      onChange={(e) => setSearch(e.target.value)}
                    />
                  </div>
                </form>
                <div
                  className="message-body p-0 overflow-auto"
                  style={{
                    minHeight: "65vh",

                    background: "#fff",
                  }}
                >
                  {userData &&
                    userData.user
                      .filter((data) => data.id != router.query.activeuser).filter((data) => data.name.includes(search))
                      .map((data, index) => (
                        <div className="flex-shrink-0" key={index}>
                          <Link
                            href={{
                              pathname: "/",
                              query: {
                                activeuser: router.query.activeuser,
                                chatuser: data.id,
                              },
                            }}
                            legacyBehavior
                          >
                            <a style={{ textDecoration: "none" }}>
                              <div
                                className="d-flex align-items-center  chat-contact"
                                style={{ paddingLeft: "1rem" }}
                              >
                                <div className="py-2">
                                  <img
                                    src="https://dummyimage.com/50x50/000/fff"
                                    alt="Profile"
                                    width={45}
                                    className="rounded-circle"
                                  />
                                </div>
                                <div
                                  className="flex-grow-1 d-flex justify-content-between ms-3 py-3 border-bottom"
                                  style={{
                                    color: "#838383",
                                    paddingRight: "1rem",
                                  }}
                                >
                                  <div>
                                    <p
                                      className="m-0 "
                                      style={{ fontSize: "16px" }}
                                    >
                                      {data.name}
                                    </p>
                                    <p
                                      className="m-0  "
                                      style={{
                                        fontSize: "12px",
                                        textDecoration: "none",
                                      }}
                                    >
                                      {data.status}
                                    </p>
                                  </div>
                                  <div style={{ fontSize: "14px" }}>
                                    timestamp
                                  </div>
                                </div>
                              </div>
                            </a>
                          </Link>
                        </div>
                      ))}
                </div>
              </Col>
              <Col
                md={8}
                className=" p-0 position-relative"
                style={{ maxHeight: "80vh" }}
              >
                <nav className="navbar" style={{ background: "#f0f2f5" }}>
                  <div className="container-fluid h-100">
                    <div className="d-flex align-items-center my-2">
                      <div className="flex-shrink-0">
                        <img
                          src="https://dummyimage.com/50x50/000/fff"
                          alt="Profile"
                          className="rounded-circle"
                        />
                      </div>
                      <div className="flex-grow-1 ms-3">
                        {chatactiveuserData.name}
                      </div>
                    </div>
                    <div></div>
                  </div>
                </nav>
                <div
                  className="message-body px-3overflow-auto"
                  style={{
                    backgroundColor: "#ebebeb",
                    minHeight: "calc(100% - 125px)",
                  }}
                >
                  <div
                    style={{
                      background:
                        "url(https://mir-s3-cdn-cf.behance.net/project_modules/disp/2d9dd173426833.5c08f5634ff45.png)",
                      minHeight: "70vh",
                    }}
                  >
                    <div
                      className="d-flex flex-column align-items-start"
                      style={{ padding: "20px" }}
                    >
                      <p
                        className="chatScreen__text"
                        style={{
                          marginLeft: "10px",
                          backgroundColor: "#fff",
                          padding: "12px",
                          borderRadius: "20px",
                        }}
                      >
                        Hello
                      </p>
                      <p
                        className="chatScreen__text"
                        style={{
                          marginLeft: "10px",
                          backgroundColor: "#fff",
                          padding: "12px",
                          borderRadius: "20px",
                        }}
                      >
                        Hey
                      </p>
                    </div>
                  </div>
                </div>
                <div className="type-message w-100 position-absolute bottom-0 ">
                  <div className="input-group input-group-lg bg-light">
                    <input
                      type="text"
                      className="form-control border rounded-0"
                      style={{ fontSize: "16px" }}
                      placeholder="Recipient's username"
                      aria-label="Recipient's username"
                      aria-describedby="basic-addon2"
                    />
                    <span
                      className="input-group-text rounded-0"
                      id="basic-addon2"
                    >
                      <MdSend />
                    </span>
                  </div>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await axios.get("http://localhost:3000/api/user");
  const userData = await res.data;
  const activeuserData = await res.data.user;
  const userId = context.query.activeuser ? context.query.activeuser : 1;
  const activeuserDataUser = await activeuserData.find(
    (data) => data.id == userId
  );
  const chatuser = context.query.chatuser ? context.query.chatuser : 1;
  const chatactiveuserData = await activeuserData.find(
    (data) => data.id == chatuser
  );
  return {
    props: { userData, activeuserDataUser, chatactiveuserData }, // will be passed to the page component as props
  };
}
